apiVersion: v1
kind: ConfigMap
metadata:
  name: sample-job-env
  labels:
    app.kubernetes.io/name: sample-job
data:
  LOG_LEVEL: "INFO"
  OTEL_ENABLED: "true"
  OTEL_SERVICE_NAME: "sample-job"
  OTEL_SERVICE_VERSION: "dev"
  OTEL_EXPORTER_OTLP_ENDPOINT: "http://otel-collector:4318"
  OTEL_TRACES_ENABLED: "true"
  OTEL_TRACE_SAMPLE_RATE: "0.01"
  OTEL_METRICS_ENABLED: "true"
  OTEL_METRIC_EXPORT_INTERVAL: "60s"
  SAMPLE_JOB_WORK_ITEMS: "1"
  SAMPLE_JOB_FAIL: "false"
