apiVersion: v1
kind: Service
metadata:
  name: sample-service
  labels:
    app.kubernetes.io/name: sample-service
spec:
  selector:
    app.kubernetes.io/name: sample-service
  ports:
  - name: http
    port: 80
    targetPort: http
